baseURL = "http://henryscotthale.com"
title = "Henry Scott Hale"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

[params]
  avatarURL = "/images/headshot.png"
  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-xl"
  # Description to display on homepage
  description = "J.D. Candidate at Brooklyn Law School"
  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"
  
  socialIcons = [
    {name = "gmail", url = "mailto:henry.hale@brooklaw.edu"},
    {name="linkedin2",url="https://linkedin.com/in/henryscotthale/"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    # Unique identifer for a menu item
    identifier = "resume"
    url = "/resume/"
    name = "Resume"
    weight = 3

  [[menu.main]]
    identifier = "writing"
    name = "Writing"
    url = "/writing/"
    weight = 4

  [[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = 5
    
  [[menu.main]]
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/henryscotthale/"
    weight = 6
    pre = "<span data-feather='linkedin'></span>"

  [[menu.main]]
    identifier = "email"
    url = "mailto:henry.hale@brooklaw.edu"
    weight = 7
    pre = "<span data-feather='mail'></span>"

